### ISSUE TITLE
create pdf files from md files, for greater visability

### ISSUE THREAD

**Issue by regevran** [wg21il/Protocols#1]
Markdown is a good way for easily write documents and are nice to be viewed with browsers.
However, sometimes PDF format is needed.
pandoc (https://pandoc.org) can be used as the tool to convert md to pdf without effort.
first approach is to use this tool as simple as possible and to evolve with it as needed.

**Comment by YehezkelShB** [comment]
Why pdf? Why not html?

**Comment by regevran** [comment]
Actually pandocs can have both easily.
The only reason I suggested a PDF is to have the documents in a printable format.
Markdown and HTML are both equal as being digital view able but non printable.

**Comment by YehezkelShB** [comment]
Ah, scratch that. We have HTML automatically generated by GitHub and placed in github.io, if configured correctly. Never mind

**Comment by regevran** [comment]
we have it
